//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace AccountMgmt.DB
{
	/// <summary>
	/// Database       : accounts
	/// Data Source    : accounts
	/// Server Version : 3.24.0
	/// </summary>
	public partial class AccountsDB : LinqToDB.Data.DataConnection
	{
		public ITable<Transaction> Transactions { get { return this.GetTable<Transaction>(); } }

		public AccountsDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public AccountsDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();
	}

	[Table("Transactions")]
	public partial class Transaction
	{
		[Column("account_id"), PrimaryKey, NotNull] public string AccountId { get; set; } // varchar(36)
		[Column("balance"),                NotNull] public int    Balance   { get; set; } // int
	}

	public static partial class TableExtensions
	{
		public static Transaction Find(this ITable<Transaction> table, string AccountId)
		{
			return table.FirstOrDefault(t =>
				t.AccountId == AccountId);
		}
	}
}

#pragma warning restore 1591
